### ISSUE TITLE
orders-web build failure: Provider io.quarkus.runtime.configuration.TemporaryConfigSourceProvider not found

### ISSUE THREAD

**Issue by deki** [aws-samples/designing-cloud-native-microservices-on-aws#5]
Followed the steps in docs/05-deploy-applications-by-cdk/README.md but the Maven build for orders-web failed with:
`Exception in thread "main" java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: Provider io.quarkus.runtime.configuration.TemporaryConfigSourceProvider not found`

**Comment by humank** [comment]
Thanks for the findings, @deki.

This issue is reproducible from my side, and I found it's a mistake from my previous update. By upgrading Quarkus to GA 1.x version, the quarkus runtime configSourceProvider is no longer to declare by self but naturally buit-in GA jar files. I had fixed this issue and feel free to run it again.
